INSERT INTO `CLUB-STADIUM` VALUES('Liverpool','Anfield');
INSERT INTO `CLUB-STADIUM` VALUES('Manchester City','Etihad Stadium');
INSERT INTO `CLUB-STADIUM` VALUES('Manchester United','Old Trafford');
INSERT INTO `CLUB-STADIUM` VALUES('Newcastle',"St. James' Park");
INSERT INTO `CLUB-STADIUM` VALUES('Southampton',"St. Mary's Stadium");
INSERT INTO `CLUB-STADIUM` VALUES('Tottenham','Tottenham Hotspur Stadium');
INSERT INTO `CLUB-STADIUM` VALUES('West Ham','London Stadium');
INSERT INTO `CLUB-STADIUM` VALUES ('Arsenal', 'Emirates Stadium');
INSERT INTO `CLUB-STADIUM` VALUES ('Aston Villa', 'Villa Park');
INSERT INTO `CLUB-STADIUM` VALUES ('Brighton', 'Amex Stadium');
INSERT INTO `CLUB-STADIUM` VALUES ('Chelsea', 'Stamford Bridge');
INSERT INTO `CLUB-STADIUM` VALUES ('Crystal Palace', 'Selhurst Park');
INSERT INTO `CLUB-STADIUM` VALUES ('Everton', 'Goodison Park');
INSERT INTO `CLUB-STADIUM` VALUES ('Leeds United', 'Elland Road');
INSERT INTO `CLUB-STADIUM` VALUES ('Leicester City', 'King Power Stadium');