INSERT INTO FIXTURES(`Home Club`,`Away Club`) VALUES("Aston Villa","Arsenal");
INSERT INTO FIXTURES(`Home Club`,`Away Club`) VALUES("Brighton","Aston Villa");
INSERT INTO FIXTURES(`Home Club`,`Away Club`) VALUES("Chelsea","Brighton");
INSERT INTO FIXTURES(`Home Club`,`Away Club`) VALUES("Crystal Palace","Chelsea");
INSERT INTO FIXTURES(`Home Club`,`Away Club`) VALUES("Everton","Crystal Palace");
INSERT INTO FIXTURES(`Home Club`,`Away Club`) VALUES("Leeds United","Everton");
INSERT INTO FIXTURES(`Home Club`,`Away Club`) VALUES("Leicester City","Leeds United");
INSERT INTO FIXTURES(`Home Club`,`Away Club`) VALUES("Liverpool","Leicester City");
INSERT INTO FIXTURES(`Home Club`,`Away Club`) VALUES("Manchester City","Liverpool");
INSERT INTO FIXTURES(`Home Club`,`Away Club`) VALUES("Manchester United","Manchester City");
INSERT INTO FIXTURES(`Home Club`,`Away Club`) VALUES("Newcastle","Manchester United");
INSERT INTO FIXTURES(`Home Club`,`Away Club`) VALUES("Southampton","Newcastle");
INSERT INTO FIXTURES(`Home Club`,`Away Club`) VALUES("Tottenham","Southampton");
INSERT INTO FIXTURES(`Home Club`,`Away Club`) VALUES("West Ham","Tottenham");
INSERT INTO FIXTURES(`Home Club`,`Away Club`) VALUES("Arsenal","West Ham");
INSERT INTO FIXTURES (`Home Club`, `Away Club`) VALUES('Arsenal', 'Aston Villa');
INSERT INTO FIXTURES (`Home Club`, `Away Club`) VALUES('Aston Villa', 'Brighton');
INSERT INTO FIXTURES (`Home Club`, `Away Club`) VALUES('Brighton', 'Chelsea');
INSERT INTO FIXTURES (`Home Club`, `Away Club`) VALUES('Chelsea', 'Crystal Palace');
INSERT INTO FIXTURES (`Home Club`, `Away Club`) VALUES('Crystal Palace', 'Everton');
INSERT INTO FIXTURES (`Home Club`, `Away Club`) VALUES('Everton', 'Leeds United');
INSERT INTO FIXTURES (`Home Club`, `Away Club`) VALUES('Leeds United', 'Leicester City');
INSERT INTO FIXTURES (`Home Club`, `Away Club`) VALUES('Leicester City', "Liverpool");
INSERT INTO FIXTURES (`Home Club`, `Away Club`) VALUES("Liverpool", 'Manchester City');
INSERT INTO FIXTURES (`Home Club`, `Away Club`) VALUES('Manchester City', 'Manchester United');
INSERT INTO FIXTURES (`Home Club`, `Away Club`) VALUES('Manchester United', 'Newcastle');
INSERT INTO FIXTURES (`Home Club`, `Away Club`) VALUES('Newcastle', 'Southampton');
INSERT INTO FIXTURES (`Home Club`, `Away Club`) VALUES('Southampton', 'Tottenham');
INSERT INTO FIXTURES (`Home Club`, `Away Club`) VALUES('Tottenham', 'West Ham');
INSERT INTO FIXTURES (`Home Club`, `Away Club`) VALUES('West Ham', 'Arsenal');
