INSERT INTO KITS VALUES("Arsenal", "Home", "Red", "White", "Red");
INSERT INTO KITS VALUES("Arsenal", "Away", "White", "Red", "White");
INSERT INTO KITS VALUES("Arsenal", "Alternate", "Blue", "Blue", "Blue");
INSERT INTO KITS VALUES("Aston Villa", "Home", "Red", "White", "Blue");
INSERT INTO KITS VALUES("Aston Villa", "Away", "Black", "Black", "Black");
INSERT INTO KITS VALUES("Aston Villa", "Alternate", "Grey", "Dark Blue", "White");
INSERT INTO KITS VALUES("Brighton", "Home", "Purple", "White", "Purple");
INSERT INTO KITS VALUES("Brighton", "Away", "Yellow", "Purple", "Yellow");
INSERT INTO KITS VALUES("Brighton", "Alternate", "Black", "Black", "Black");
INSERT INTO KITS VALUES("Chelsea", "Home", "Blue", "Blue", "White");
INSERT INTO KITS VALUES("Chelsea", "Away", "Grey", "Grey", "Black");
INSERT INTO KITS VALUES("Chelsea", "Alternate", "Orange", "Orange", "Blue");
INSERT INTO KITS VALUES("Crystal Palace", "Home", "Blue", "Blue", "Blue");
INSERT INTO KITS VALUES("Crystal Palace", "Away", "White", "White", "White");
INSERT INTO KITS VALUES("Crystal Palace", "Alternate", "Black", "Black", "Black");
INSERT INTO KITS VALUES("Everton", "Home", "Blue", "White", "White");
INSERT INTO KITS VALUES("Everton", "Away", "Yellow", "Blue", "Yellow");
INSERT INTO KITS VALUES("Everton", "Alternate", "Green", "Black", "Green");
INSERT INTO KITS VALUES("Leeds United", "Home", "White", "White", "White");
INSERT INTO KITS VALUES("Leeds United", "Away", "Blue-Black", "Black", "Black");
INSERT INTO KITS VALUES("Leeds United", "Alternate", "red", "Red", "Red");
INSERT INTO KITS VALUES("Leicester City", "Home", "Blue", "Blue", "Blue");
INSERT INTO KITS VALUES("Leicester City", "Away", "White", "White", "White");
INSERT INTO KITS VALUES("Leicester City", "Alternate", "Maroon", "Maroon", "Maroon");
INSERT INTO KITS VALUES("Liverpool", "Home", "Red", "Red", "Red");
INSERT INTO KITS VALUES("Liverpool", "Away", "Cyan", "Cyan", "Cyan");
INSERT INTO KITS VALUES("Liverpool", "Alternate", "Black", "Black", "Black");
INSERT INTO KITS VALUES('Manchester City','Home','Light Blue','White','Light Blue');
INSERT INTO KITS VALUES('Manchester City','Away','Black','Black','Black');
INSERT INTO KITS VALUES('Manchester City','Alternate','White','Dark Blue','White');
INSERT INTO KITS VALUES('Manchester United','Home','Red','White','Black');
INSERT INTO KITS VALUES('Manchester United','Away','Black','Black','Black');
INSERT INTO KITS VALUES('Manchester United','Alternate','White-Black','Black','White');
INSERT INTO KITS VALUES('Newcastle','Home','White-Black','Black','Black');
INSERT INTO KITS VALUES('Newcastle','Away','Yellow','Yellow','Yellow');
INSERT INTO KITS VALUES('Newcastle','Alternate','Purple','Black','Black');
INSERT INTO KITS VALUES('Southampton','Home','Red-White','Black','Red-White');
INSERT INTO KITS VALUES('Southampton','Away','Dark Blue','Blue','Blue');
INSERT INTO KITS VALUES('Southampton','Alternate','White-Red','White','White-Red');
INSERT INTO KITS VALUES('Tottenham','Home','White-Dark Blue','Dark-Blue','White');
INSERT INTO KITS VALUES('Tottenham','Away','Green','Black','Black');
INSERT INTO KITS VALUES('Tottenham','Alternate','Yellow-Orange','Orange','Orange');
INSERT INTO KITS VALUES('West Ham','Home','Red-Light Blue','White','White');
INSERT INTO KITS VALUES('West Ham','Away','Light Blue-Red','Light Blue','Light Blue-Red');
INSERT INTO KITS VALUES('West Ham','Alternate','Black','Black','Black');