INSERT INTO MANAGERS VALUES('Mikel', NULL, 'Arteta',' Arsenal', '1982-03-26');
INSERT INTO MANAGERS VALUES('Dean', NULL, 'Smith', 'Aston Villa', '1971-03-19');
INSERT INTO MANAGERS VALUES('Graham', NULL, 'Potter', 'Brighton', '1975-05-20');
INSERT INTO MANAGERS VALUES('Frank', NULL, 'Lampard', 'Chelsea', '1978-06-20');
INSERT INTO MANAGERS VALUES('Roy', NULL, 'Hodgson', 'Crystal Palace', '1947-08-09');
INSERT INTO MANAGERS VALUES('Carlo', NULL, 'Anceloti', 'Everton', '1959-06-10');
INSERT INTO MANAGERS VALUES('Marcelo', NULL, 'Bielsa', 'Leeds United', '1955-07-21');
INSERT INTO MANAGERS VALUES('Brendan', NULL, 'Rodgers', 'Leicester City', '1973-01-26');
INSERT INTO MANAGERS VALUES('Jurgen', NULL, 'Klopp', 'Liverpool', '1967-06-16');
INSERT INTO MANAGERS VALUES('Josep', NULL, 'Guardiola', 'Manchester City', '1971-01-18');
INSERT INTO MANAGERS VALUES('Ole', 'Gunnar', 'Solskjaer', 'Manchester United', '1973-02-26');
INSERT INTO MANAGERS VALUES('Steve', NULL, 'Bruce', 'Newcastle', '1960-12-31');
INSERT INTO MANAGERS VALUES('Ralph', NULL, 'Hasenhuttl', 'Southampton', '1967-08-09');
INSERT INTO MANAGERS VALUES('Jose', NULL,'Mourinho', 'Tottenham', '1963-01-26');
INSERT INTO MANAGERS VALUES('David', NULL, 'Moyes', 'West Ham', '1963-04-25');
